version: '3'
services:
  chat-server:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - /app/node_modules
  
  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: